### ISSUE TITLE
There is no interface layer with other third party library

### ISSUE THREAD

**Issue by keyhooon** [MaJerle/lwgsm#36]
Hello @MaJerle

This is very nice and great code.

I am using your library successfully for sim808 and work with mqtt app.

i am confused how i can use from other library on top of your code?, how can use lwip or new library that ST released which name is Network library or Cloud general library on top of your code?

do you have plan for implement standard interface that we can use other library on top of your code?

for example if you implement interface like netif in lwip, your library can work with other third party libraries.

**Comment by MaJerle** [comment]
What do you believe is standard interface?

**Comment by keyhooon** [comment]
For example,Release Notes for
STM32 Network Library Says : "The STM32 Network Library is a middleware providing network services on STM32 devices. It provides a socket API (BSD like style) with support of secure or non secure connection and an API to control the lifecycle of the network adapters.

Three classes of network adapters are supported WIFI, Ethernet and Cellular. Different WIFI modules are supported from third party vendors."
This library provide standard Socket API (BSD like style), then other library that based on socket API can use it and provide feature on top of this socket API.
This library (Network Library) needs netif layer files to recognize type of network.
i'm not good in English, sry for that.

**Comment by keyhooon** [comment]
For example i need TLS on MQTT, if you prepare socket layer like BSD socket, i can implement TLS on that and then Mqtt base on TLS socket.

**Comment by MaJerle** [comment]
Most likely you need TLS on transport layer itself, so on TCP. This means starting SSL connection from modem point of view (that has full TCPIP stack).
